
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int QUES = 18;
  public static final int DIVIDE = 33;
  public static final int CHAR = 6;
  public static final int STRINGLIT = 29;
  public static final int LEFTSBR = 24;
  public static final int SEMI = 10;
  public static final int INT = 5;
  public static final int UNRYPLUS = 49;
  public static final int MINUS = 35;
  public static final int NOT = 48;
  public static final int AND = 42;
  public static final int LT = 36;
  public static final int INTLIT = 26;
  public static final int OR = 43;
  public static final int BOOL = 7;
  public static final int CLASS = 2;
  public static final int INC = 46;
  public static final int GEQ = 39;
  public static final int PLUS = 34;
  public static final int ASSIGN = 45;
  public static final int IF = 11;
  public static final int ID = 3;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int PRINTLINE = 15;
  public static final int TRUE = 30;
  public static final int error = 1;
  public static final int NEQ = 41;
  public static final int VOID = 9;
  public static final int FLOATLIT = 27;
  public static final int EEQ = 40;
  public static final int COM = 19;
  public static final int COL = 44;
  public static final int TIMES = 32;
  public static final int CHARLIT = 28;
  public static final int UNRYMINUS = 50;
  public static final int ELSE = 17;
  public static final int READ = 13;
  public static final int FINAL = 4;
  public static final int WHILE = 12;
  public static final int FLOAT = 8;
  public static final int LEQ = 38;
  public static final int RIGHTCBR = 23;
  public static final int RIGHTBR = 21;
  public static final int DEC = 47;
  public static final int FALSE = 31;
  public static final int GT = 37;
  public static final int LEFTBR = 20;
  public static final int LEFTCBR = 22;
  public static final int PRINT = 14;
  public static final int RIGHTSBR = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ID",
  "FINAL",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "VOID",
  "SEMI",
  "IF",
  "WHILE",
  "READ",
  "PRINT",
  "PRINTLINE",
  "RETURN",
  "ELSE",
  "QUES",
  "COM",
  "LEFTBR",
  "RIGHTBR",
  "LEFTCBR",
  "RIGHTCBR",
  "LEFTSBR",
  "RIGHTSBR",
  "INTLIT",
  "FLOATLIT",
  "CHARLIT",
  "STRINGLIT",
  "TRUE",
  "FALSE",
  "TIMES",
  "DIVIDE",
  "PLUS",
  "MINUS",
  "LT",
  "GT",
  "LEQ",
  "GEQ",
  "EEQ",
  "NEQ",
  "AND",
  "OR",
  "COL",
  "ASSIGN",
  "INC",
  "DEC",
  "NOT",
  "UNRYPLUS",
  "UNRYMINUS"
  };
}

